LIB = ../libft.a

HEADER = ../header/libft.h

ft_strcmp:
	gcc ft_strcmp_main.c $(LIB)

ft_strmap:
	gcc ft_strmap_main.c $(LIB)

ft_putchar_fd:
	gcc ft_putchar_main.c $(LIB)

ft_putnbr_fd: 
	gcc ft_putnbr_main.c $(LIB)

ft_atoi:
	gcc ft_atoi_main.c $(LIB)

ft_strclr:
	gcc ft_strclr_main.c $(LIB)

ft_strcat:
	gcc ft_strcat_main.c $(LIB)

fclean:
	rm -rf 
