LIB = ../libft.a

HEADER = ../header/libft.h

ft_putchar_fd:
	gcc ft_putchar_main.c $(LIB)

ft_putnbr_fd: 
	gcc ft_putnbr_main.c $(LIB)

ft_atoi:
	gcc ft_atoi_main.c $(LIB)

ft_strclr:
	gcc ft_strclr_main.c ../obligatoire/ft_strclr.c ../obligatoire/ft_strlen.c

fclean:
	rm -rf 
