LIB = ../libft.a

HEADER = ../header/libft.h

ft_putchar_fd:
	gcc ft_putchar_main.c $(LIB)

ft_putnbr: 
	gcc ft_putnbr_main.c $(LIB)

ft_atoi:
	gcc ft_atoi_main.c ../obligatoire/ft_putnbr.c ../obligatoire/ft_putchar.c ../obligatoire/ft_putchar_fd.c ../obligatoire/ft_putstr_fd.c ../obligatoire/ft_putnbr_fd.c ../obligatoire/ft_atoi.c

ft_strclr:
	gcc ft_strclr_main.c ../obligatoire/ft_strclr.c ../obligatoire/ft_strlen.c

fclean:
	rm -rf 
